version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: asset_inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/asset_inventory
      # InsightVM API Configuration
      RAPID7_INSIGHTVM_USERNAME: ${RAPID7_INSIGHTVM_USERNAME}
      RAPID7_INSIGHTVM_PASSWORD: ${RAPID7_INSIGHTVM_PASSWORD}
      # Legacy Rapid7 Configuration
      RAPID7_API_KEY: ${RAPID7_API_KEY}
      RAPID7_BASE_URL: ${RAPID7_BASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: